<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603132908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, language VARCHAR(5) NOT NULL, topic VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL, pdf_s3_key VARCHAR(500) DEFAULT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, child_id INT NOT NULL, template_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBE5A331A76ED395 ON book (user_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A331DD62C21B ON book (child_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A3315DA0FB8 ON book (template_id)');
        $this->addSql('CREATE TABLE child (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, age INT NOT NULL, gender VARCHAR(20) DEFAULT NULL, appearance VARCHAR(500) DEFAULT NULL, interests VARCHAR(500) DEFAULT NULL, pet_name VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_22B35429A76ED395 ON child (user_id)');
        $this->addSql('CREATE TABLE job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, attempts INT NOT NULL, error_message TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBD8E0F816A2B381 ON job (book_id)');
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, page_number INT NOT NULL, text TEXT DEFAULT NULL, image_prompt TEXT DEFAULT NULL, image_s3_key VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_140AB62016A2B381 ON page (book_id)');
        $this->addSql('CREATE TABLE rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D889262216A2B381 ON rating (book_id)');
        $this->addSql('CREATE INDEX IDX_D8892622A76ED395 ON rating (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_book_user ON rating (book_id, user_id)');
        $this->addSql('CREATE TABLE referral (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, rewarded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, referrer_id INT NOT NULL, referee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_73079D00798C22DB ON referral (referrer_id)');
        $this->addSql('CREATE INDEX IDX_73079D004A087CA2 ON referral (referee_id)');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan VARCHAR(10) NOT NULL, status VARCHAR(20) NOT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, current_period_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, books_used_this_month INT NOT NULL, books_limit INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_user_id ON subscription (user_id)');
        $this->addSql('CREATE TABLE template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, description VARCHAR(500) NOT NULL, category VARCHAR(50) NOT NULL, age_min INT NOT NULL, age_max INT NOT NULL, prompt_blueprint TEXT NOT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, google_id VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, avatar_url VARCHAR(500) DEFAULT NULL, referral_code VARCHAR(8) DEFAULT NULL, refresh_token VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976F5C865 ON "user" (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6496447454A ON "user" (referral_code)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331DD62C21B FOREIGN KEY (child_id) REFERENCES child (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3315DA0FB8 FOREIGN KEY (template_id) REFERENCES template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE child ADD CONSTRAINT FK_22B35429A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F816A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62016A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D889262216A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D00798C22DB FOREIGN KEY (referrer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D004A087CA2 FOREIGN KEY (referee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331A76ED395');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331DD62C21B');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3315DA0FB8');
        $this->addSql('ALTER TABLE child DROP CONSTRAINT FK_22B35429A76ED395');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT FK_FBD8E0F816A2B381');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB62016A2B381');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D889262216A2B381');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D8892622A76ED395');
        $this->addSql('ALTER TABLE referral DROP CONSTRAINT FK_73079D00798C22DB');
        $this->addSql('ALTER TABLE referral DROP CONSTRAINT FK_73079D004A087CA2');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3A76ED395');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE child');
        $this->addSql('DROP TABLE job');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE rating');
        $this->addSql('DROP TABLE referral');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE template');
        $this->addSql('DROP TABLE "user"');
    }
}
